### ISSUE TITLE
Wiiflow compatibility missing?

### ISSUE THREAD

**Issue by saulfabregwiivc** [Wiimpathy/Neocd-Wii#3]
Is there any chance for make NeoCD-Wii compatible with Wiiflow as a plugin?
Because as far as i know this emulator is the only real NeoGeo CD emulator for Wii...

But it isn't Wiiflow-compatible... :(

Will you make this emulator compatible with Wiiflow?

EDIT: I'm really interested in it since some exclusive NeoGeo CD games weren't released as MVS/AES games (NeoGeo CD Special, ADK World, Ironclad, Crossed Swords 2, KOF '96 Neo Collection, etc.)

**Comment by Wiimpathy** [comment]
@saulfabregwiivc
There are a few exclusive games indeed. And better soundtracks sometimes.
However, there's a nasty video bug I've never managed to fix properly.  The other problem would be to compile on more recent devkit.

In short, I don't find worth the effort to make it plugin compatible.

There might be other options for NeoGeoCD.
1. Using https://github.com/libretro/FBNeo and only keep the neogeo driver.
2. Using this core : https://github.com/libretro/neocd_libretro

**Comment by saulfabregwiivc** [comment]
> @saulfabregwiivc There are a few exclusive games indeed. And better soundtracks sometimes. However, there's a nasty video bug I've never managed to fix properly. The other problem would be to compile on more recent devkit.
> 
> In short, I don't find worth the effort to make it plugin compatible.
> 
> There might be other options for NeoGeoCD.
> 
> 1. Using https://github.com/libretro/FBNeo and only keep the neogeo driver.
> 2. Using this core : https://github.com/libretro/neocd_libretro

Thanks for the suggestions @Wiimpathy, but...

Are the cores of FBNeo NeoGeo (for Wii of course) compatible with NeoGeo CD? And how i can setup it properly for play NeoGeo CD games on Wii?
And what version of RA Wii should i use? (Libretro official RA or RA-HEXAECO by SuperrSonic?)

Thanks!

**Comment by Wiimpathy** [comment]
Yes, FBNeo can emulate NeoGeo CD too. Only libretro official.

Yeah, there's a but. That requires some work. 
First, you need to compile the core. And for this core, the dol is much too large. Only the neogeo driver should be kept.
Last time I tried there was issue with audio and the subsystem menu or whatever it's called.
Maybe using the other neocd_libretro is worth a try.

**Comment by saulfabregwiivc** [comment]
> Maybe using the other neocd_libretro is worth a try.

Haha, it technically works on the Nintendo Wii even if not officially.
I've posted a functional Wii build here:
https://gbatemp.net/threads/unofficial-neocd-libretro-snk-neogeo-cd-emulator-core-for-the-wii-powered-by-retroarch.630584/

Closing this issue.
